interface DropdownItem {
  label: string;
  value: string;
  icon?: string;
  color?: string;
}
export const US_STATES: DropdownItem[] = [
  { label: "آلاباما (AL)", value: "AL" },
  { label: "آلاسکا (AK)", value: "AK" },
  { label: "آریزونا (AZ)", value: "AZ" },
  { label: "آرکانزاس (AR)", value: "AR" },
  { label: "کالیفورنیا (CA)", value: "CA" },
  { label: "کلورادو (CO)", value: "CO" },
  { label: "کانتیکت (CT)", value: "CT" },
  { label: "دلاویر (DE)", value: "DE" },
  { label: "فلوریدا (FL)", value: "FL" },
  { label: "جورجیا (GA)", value: "GA" },
  { label: "هاوایی (HI)", value: "HI" },
  { label: "آیداهو (ID)", value: "ID" },
  { label: "ایلینوی (IL)", value: "IL" },
  { label: "ایندیانا (IN)", value: "IN" },
  { label: "آیوا (IA)", value: "IA" },
  { label: "کانزاس (KS)", value: "KS" },
  { label: "کنتاکی (KY)", value: "KY" },
  { label: "لوئیزیانا (LA)", value: "LA" },
  { label: "مین (ME)", value: "ME" },
  { label: "مریلند (MD)", value: "MD" },
  { label: "ماساچوست (MA)", value: "MA" },
  { label: "میشیگان (MI)", value: "MI" },
  { label: "مینیسوتا (MN)", value: "MN" },
  { label: "میسیسیپی (MS)", value: "MS" },
  { label: "میزوری (MO)", value: "MO" },
  { label: "مونتانا (MT)", value: "MT" },
  { label: "نبراسکا (NE)", value: "NE" },
  { label: "نوادا (NV)", value: "NV" },
  { label: "نیوهمپشایر (NH)", value: "NH" },
  { label: "نیوجرسی (NJ)", value: "NJ" },
  { label: "نیو مکزیکو (NM)", value: "NM" },
  { label: "نیویورک (NY)", value: "NY" },
  { label: "کارولینای شمالی (NC)", value: "NC" },
  { label: "کارولینای جنوبی (SC)", value: "SC" },
  { label: "اوهایو (OH)", value: "OH" },
  { label: "اوکلاهما (OK)", value: "OK" },
  { label: "اوریگون (OR)", value: "OR" },
  { label: "پنسیلوانیا (PA)", value: "PA" },
  { label: "رود آیلند (RI)", value: "RI" },
  { label: "داکوتای جنوبی (SD)", value: "SD" },
  { label: "تنسی (TN)", value: "TN" },
  { label: "تگزاس (TX)", value: "TX" },
  { label: "یوتا (UT)", value: "UT" },
  { label: "ورمونت (VT)", value: "VT" },
  { label: "ویرجینیا (VA)", value: "VA" },
  { label: "واشنگتن (WA)", value: "WA" },
  { label: "ویرجینیای غربی (WV)", value: "WV" },
  { label: "ویسکانسین (WI)", value: "WI" },
  { label: "وایومینگ (WY)", value: "WY" },
];
